-- CreateEnum
CREATE TYPE "TreeStatus" AS ENUM ('PLANTED', 'LISTED', 'VERIFYING', 'VERIFIED', 'PLANTERS_PAID', 'VERIFIERS_PAID', 'MATURED');

-- AlterTable
ALTER TABLE "Tree" ADD COLUMN     "status" "TreeStatus" NOT NULL DEFAULT 'PLANTED';
